#!/usr/bin/env python3
"""Compile the committed boards into the component.

A cartridge imports nothing -- no filesystem, no clock, no sockets (docs/cartridge.md §4) -- so a
board cannot be read at run time. Every file in maps/ becomes an `include_str!` in a generated,
committed module instead, exactly as plugin.json and cartridge.json are generated and committed:
an artifact nobody hand-edits cannot drift from the thing it was made from.
"""
import os
import sys

HEADER = '''//! GENERATED by build.sh from `maps/` -- do not edit.
//!
//! The cartridge imports nothing: no filesystem, no clock, no sockets (`docs/cartridge.md` §4),
//! so a board cannot be read at run time. Every committed map is compiled in instead, which is
//! also what makes a map edit an engine-digest change -- and therefore refused while a season is
//! live, on the same rails a rules change already runs on.

pub const MAPS: [(&str, &str); %d] = [
%s
];
'''


def main(here):
    mapdir = os.path.join(here, "maps")
    names = sorted(f[:-5] for f in os.listdir(mapdir) if f.endswith(".json"))
    if not names:
        sys.exit("no boards in maps/ -- generate one with `cargo run --bin mapgen`")
    rows = "\n".join(
        '    ("%s", include_str!("../maps/%s.json")),' % (n, n) for n in names
    )
    out = os.path.join(here, "src", "maps_gen.rs")
    with open(out, "w") as f:
        f.write(HEADER % (len(names), rows))
    print("    embedded %d boards" % len(names))


if __name__ == "__main__":
    main(sys.argv[1])
