//! GENERATED by build.sh from `maps/` -- do not edit.
//!
//! The cartridge imports nothing: no filesystem, no clock, no sockets (`docs/cartridge.md` §4),
//! so a board cannot be read at run time. Every committed map is compiled in instead, which is
//! also what makes a map edit an engine-digest change -- and therefore refused while a season is
//! live, on the same rails a rules change already runs on.

pub const MAPS: [(&str, &str); 24] = [
    ("cell-00", include_str!("../maps/cell-00.json")),
    ("cell-01", include_str!("../maps/cell-01.json")),
    ("cell-02", include_str!("../maps/cell-02.json")),
    ("cell-03", include_str!("../maps/cell-03.json")),
    ("cell-04", include_str!("../maps/cell-04.json")),
    ("cell-05", include_str!("../maps/cell-05.json")),
    ("cell-06", include_str!("../maps/cell-06.json")),
    ("cell-07", include_str!("../maps/cell-07.json")),
    ("maze-00", include_str!("../maps/maze-00.json")),
    ("maze-01", include_str!("../maps/maze-01.json")),
    ("maze-02", include_str!("../maps/maze-02.json")),
    ("maze-03", include_str!("../maps/maze-03.json")),
    ("maze-04", include_str!("../maps/maze-04.json")),
    ("maze-05", include_str!("../maps/maze-05.json")),
    ("maze-06", include_str!("../maps/maze-06.json")),
    ("maze-07", include_str!("../maps/maze-07.json")),
    ("standard-00", include_str!("../maps/standard-00.json")),
    ("standard-01", include_str!("../maps/standard-01.json")),
    ("standard-02", include_str!("../maps/standard-02.json")),
    ("standard-03", include_str!("../maps/standard-03.json")),
    ("standard-04", include_str!("../maps/standard-04.json")),
    ("standard-05", include_str!("../maps/standard-05.json")),
    ("standard-06", include_str!("../maps/standard-06.json")),
    ("standard-07", include_str!("../maps/standard-07.json")),
];
